[package]
name = "example-json"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "json"
path = "src/main.rs"
doc = false

[dependencies]
tsukuyomi = "0.2"
serde = { version = "1.0", features = ["derive"] }
futures = "0.1.21"
pretty_env_logger = "0.2.3"
log = "0.4"
